### PR TITLE
requests==2.28.1 and urllib3==1.26.12

### PR DESCRIPTION
**Pull request by bhawanibytes**
### **To solve Vercel deployment issue**

older versions in requirements.txt are causing deployment issues for serverless function on vercel.

To solve the issue - 

_**requests==2.28.1
urllib3==1.26.12**_

these need to be updated to respective versions!

### CODE REVIEW

**Comment by bhawanibytes** [comment]
@novatorem   Issue of deployment to Vercel is resolved. please take a look at PR.

**Review by bhawanibytes — COMMENTED** [review]
All good

**Comment by bhawanibytes** [comment]
@johnpc @T0biii @AlexandrosAlexiou @novatorem 

Please review the PR

**Comment by T0biii** [comment]
@bhawanibytes pls dont tag me. I cant help here.
You need to be patient till the owner reviews this pr
seems to be also a duplicate of #90 maybe

**Comment by bhawanibytes** [comment]
> @bhawanibytes pls dont tag me. I cant help here. You need to be patient till the owner reviews this pr seems to be also a duplicate of #90 maybe

I'm sorry. I thought you were a member of the owner's team. I am new to GitHub. And while #90 still has some conflicts, mine is working fine.

**Pull request closed without merging**
